jdk:
  - openjdk21

env:
  ANDROID_HOME: /opt/android-sdk
  ANDROID_SDK_ROOT: /opt/android-sdk
  PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:$PATH

before_install:
  - sudo apt-get update && sudo apt-get install -y wget unzip
  - wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
  - mkdir -p $ANDROID_HOME/cmdline-tools
  - unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
  - mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

  # 接受 License 並安裝 SDK/NDK
  - yes | sdkmanager --licenses
  - sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;28.0.12674087"

  # 把 local.properties 寫到專案根目錄
  - echo "sdk.dir=$ANDROID_HOME" > /home/jitpack/build/local.properties

  - cat /home/jitpack/build/local.properties

build:
  commands:
    - ./gradlew :android-gif-drawable:assembleRelease